#ifndef MOCKOS_CONSTANTS_H
#define MOCKOS_CONSTANTS_H

// All enumeration codes
enum error_code {
    SUCCESS,
    INVALID_IMAGE,
    SIZE_MISMATCH,
    APPEND_NOT_SUPPORTED,
    FILE_ALREADY_EXISTS,
    FILE_IS_NULL,
    INVALID_FILE_TYPE,
    FILE_NOT_OPEN,
    FILE_DOES_NOT_EXIST,
    FILE_IS_OPEN,
    PASSWORDS_DONT_MATCH,
    INSERTION_FAILED,
    USER_QUIT,
    FAILED_TO_CREATE_FILE,
    FAILED_TO_ADD_FILE_TO_FS,
    COMMAND_FAILED,
    QUIT_NO_SAVE,
    COMMAND_INPUT_MISMATCH,
    COPY_ERROR,
    DELETION_FAILED
};

#endif //MOCKOS_CONSTANTS_H